### ISSUE TITLE
Error using `DataPassthroughRequest` with `PATCH` method

### ISSUE THREAD

**Issue by ahmontero** [merge-api/merge-sdk-python#42]
When I am using `DataPassthroughRequest` object to send data to ATS using a `PATCH` or `POST` method,  I get an error.

Example:
```python
data = {"id": 123}
data_passthrough_request = DataPassthroughRequest('PATCH', "some/path/", data=data)
PassthroughApi(client).passthrough_create(data_passthrough_request) <-- raises an error
```
Error:
```
MergePythonSDK.shared.exceptions.ApiTypeError: Invalid type for variable 'data'. Required value type is one of [NoneType, NoneType, str] and passed type was dict at ['data']
```
How can I send data using `DataPassthroughRequest`? Before the last lib update I was sending `data` as a `dict`.

**Comment by ahmontero** [comment]
For now I am using this code that seems to work:
```python
import json
.
.
.
data = json.dumps(data)
DataPassthroughRequest('PATCH', "some/path/", data=data)
.
.
.
```

**Comment by ankitd33** [comment]
Ah yeah sorry for the confusion - so it actually never should have worked with data as a dict as it has always been expecting a string. It looks like a recent change actually started enforcing that typing.
